spring:
  profiles:
    active: dev # デフォルトは開発用
  application:
    name: footprint
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 共通のビジネスロジック用設定
app:
  image:
    max-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: jp.i432kg.footprint.infrastructure.datasource.typehandler
  mapper-locations: classpath:jp/i432kg/footprint/infrastructure/datasource/mapper/**/*.xml