spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footprint_local?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=utf8
    username: footprint
    password: footprint
  jpa:
    hibernate:
      ddl-auto: none

# 開発環境はローカルストレージを使用
app:
  storage:
    type: LOCAL
    local:
      root-dir: storage/local
    image-base-url: /images/

  frontend:
    entries:
      login:
        js: "http://localhost:5173/src/entries/login/main.js"
        css: [ ]
      map:
        js: "http://localhost:5173/src/entries/map/main.js"
        css: [ ]
      mypage:
        js: "http://localhost:5173/src/entries/mypage/main.js"
        css: [ ]
      search:
        js: "http://localhost:5173/src/entries/search/main.js"
        css: [ ]
      timeline:
        js: "http://localhost:5173/src/entries/timeline/main.js"
        css: [ ]
