spring:
  datasource:
    url: jdbc:h2:mem:footprintdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

# 開発環境はローカルストレージを使用
app:
  storage:
    type: LOCAL
    local:
      root-dir: storage/local
    image-base-url: /images/

  frontend:
    entries:
      login:
        js: "http://localhost:5173/src/entries/login/main.js"
      map:
        js: "http://localhost:5173/src/entries/map/main.js"
      mypage:
        js: "http://localhost:5173/src/entries/mypage/main.js"
      search:
        js: "http://localhost:5173/src/entries/search/main.js"
      timeline:
        js: "http://localhost:5173/src/entries/timeline/main.js"